#!/bin/sh

set -xe

apk add --update linux-rpi linux-rpi4 raspberrypi-bootloader 
apk add alpine-conf

echo "modules=loop,squashfs,sd-mod,usb-storage root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes console=tty1 rootwait quiet" > /boot/cmdline.txt

cat <<EOF > /boot/config.txt
[pi3]
kernel=vmlinuz-rpi
initramfs initramfs-rpi
[pi3+]
kernel=vmlinuz-rpi
initramfs initramfs-rpi
[pi4]
enable_gic=1
kernel=vmlinuz-rpi4
initramfs initramfs-rpi4
[all]
arm_64bit=1
include usercfg.txt
EOF

cat <<EOF > /boot/usercfg.txt
EOF

# fstab
cat <<EOF > /etc/fstab
/dev/mmcblk0p1  /boot           vfat    defaults          0       2
/dev/mmcblk0p2  /               ext4    defaults,noatime  0       1
EOF

cat <<EOF >> /etc/sysctl.conf
vm.vfs_cache_pressure=500
vm.swappiness=100
vm.dirty_background_ratio=1
vm.dirty_ratio=50
EOF

cat <<EOF >> /etc/local.d/cpufreq.start
#!/bin/sh
for cpu in /sys/devices/system/cpu/cpufreq/policy*; do
  echo performance > ${cpu}/scaling_governor
done
EOF

# 配置GPU
cat <<EOF > /boot/usercfg.txt
dtoverlay=vc4-kms-v3d
max_framebuffers=2
gpu_mem=512
hdmi_enable_4kp60=1
EOF


chmod +x /etc/local.d/cpufreq.start
rc-update add local default
