#!/bin/sh

set -xe

apk add --update linux-rpi linux-rpi4 raspberrypi-bootloader 
apk add alpine-conf

echo "modules=loop,squashfs,sd-mod,usb-storage root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes console=tty1 rootwait quiet usbhid.mousepoll=0" > /boot/cmdline.txt

cat <<EOF > /boot/config.txt
[pi3]
kernel=vmlinuz-rpi
initramfs initramfs-rpi
[pi3+]
kernel=vmlinuz-rpi
initramfs initramfs-rpi
[pi4]
enable_gic=1
kernel=vmlinuz-rpi4
initramfs initramfs-rpi4
[all]
arm_64bit=1
include usercfg.txt
EOF

cat <<EOF > /boot/usercfg.txt
EOF

# fstab
cat <<EOF > /etc/fstab
/dev/mmcblk0p1  /boot           vfat    defaults          0       2
/dev/mmcblk0p2  /               ext4    defaults,noatime  0       1
EOF

cat <<EOF >> /etc/sysctl.conf
vm.vfs_cache_pressure=500
vm.swappiness=100
vm.dirty_background_ratio=1
vm.dirty_ratio=50
EOF

cat <<EOF >> /etc/local.d/cpufreq.start
#!/bin/sh
for cpu in /sys/devices/system/cpu/cpufreq/policy*; do
  echo performance > ${cpu}/scaling_governor
done
EOF

# 配置GPU
cat <<EOF > /boot/usercfg.txt
dtoverlay=vc4-kms-v3d
max_framebuffers=2
gpu_mem=512
hdmi_enable_4kp60=1

#2560x1440(2k),60hz,16:8的屏幕
hdmi_cvt 2560 1440 60 3 0 0 0
#hdmi_group=2 means DMT (Display Monitor Timings; the standard typically used by monitors)
hdmi_group=2
#hdmi_mode=87 indicates the resolution mode we set before.
hdmi_mode=87
#max_framebuffer_width=2560
#max_framebuffer_height=1440
#required
hdmi_drive=1
hdmi_boost=7
#required,Enables the ignoring of EDID/display data if your display is a crappy Chinese one
hdmi_ignore_edid=0xa5000080
EOF


chmod +x /etc/local.d/cpufreq.start
rc-update add local default
