#!/bin/sh

apk add chromium

#创建x11自启动
cat <<EOF > /srv/.profile
#!/bin/sh
#start x server
exec startx
EOF

#自启动浏览器
cat <<EOF > /srv/.xinitrc
#!/bin/sh

# turn off screensaver
xset -dpms
xset s off
xset s noblank


# screen size
width="1920"
height="1080"

# url
url="file:///srv/sum.mp4"

exec chromium-browser $url --window-size=$width,$height --window-position=0,0 --kiosk --no-sandbox --full-screen --incognito --noerrdialogs --disable-translate --no-first-run --fast --fast-start --ignore-gpu-blacklist --disable-quic --enable-fast-unload --enable-tcp-fast-open ---enable-native-gpu-memory-buffers --enable-gpu-rasterization --enable-zero-copy --disable-infobars --disable-features=TranslateUI --disk-cache-dir=/tmp --enable-features=VaapiVideoEncoder,VaapiVideoDecoder,CanvasOopRasterization 

EOF

