#!/bin/sh

set -xe

cat <<EOF >> /usr/bin/after-setup
#!/bin/sh

chmod +x /bootstrap/08-driver
chmod +x /bootstrap/09-x11
chmod +x /bootstrap/10-chromium
chmod +x /bootstrap/11-chinese-font
chmod +x /bootstrap/12-docker

sh /bootstrap/08-driver
sh /bootstrap/09-x11
sh /bootstrap/10-chromium
sh /bootstrap/11-chinese-font
sh /bootstrap/12-docker

rc-update del after-setup
rm /etc/init.d/after-setup /usr/bin/after-setup

EOF

cat <<EOF >>/etc/init.d/after-setup
#!/sbin/openrc-run

command="/usr/bin/after-setup"
command_background=false

depend(){
    need net
}
EOF

chmod +x /etc/init.d/after-setup /usr/bin/after-setup
#/etc/init.d/after-setup增加到服务
rc-update add after-setup