#!/bin/sh

apk add nodejs

cat <<EOF > /etc/init.d/staticserver
#!/sbin/openrc-run

command="node /srv/staticserver/index.js &"
command_background=false

depend(){
  after modules
  need localmount
}
EOF

chmod +x /etc/init.d/staticserver
rc-update add staticserver

cat <<EOF > /etc/init.d/contentWatcher
#!/sbin/openrc-run

command="node /srv/contentWatcher/index.js &"
command_background=false

depend(){
  after modules
  need localmount
}
EOF

chmod +x /etc/init.d/contentWatcher
rc-update add contentWatcher
